complete -c flamegraph -n "__fish_use_subcommand" -s p -l pid -d 'Profile a running process by pid'
complete -c flamegraph -n "__fish_use_subcommand" -l completions -d 'Generate shell completions for the given shell'
complete -c flamegraph -n "__fish_use_subcommand" -s o -l output -d 'Output file, flamegraph.svg if not present'
complete -c flamegraph -n "__fish_use_subcommand" -s F -l freq -d 'Sampling frequency'
complete -c flamegraph -n "__fish_use_subcommand" -s c -l cmd -d 'Custom command for invoking perf/dtrace'
complete -c flamegraph -n "__fish_use_subcommand" -l notes -d 'Set embedded notes in SVG'
complete -c flamegraph -n "__fish_use_subcommand" -l min-width -d 'Omit functions smaller than <FLOAT> pixels'
complete -c flamegraph -n "__fish_use_subcommand" -l image-width -d 'Image width in pixels'
complete -c flamegraph -n "__fish_use_subcommand" -l palette -d 'Color palette' -r -f -a "hot mem io red green blue aqua yellow purple orange wakeup java perl js rust"
complete -c flamegraph -n "__fish_use_subcommand" -l perfdata
complete -c flamegraph -n "__fish_use_subcommand" -s v -l verbose -d 'Print extra output to help debug problems'
complete -c flamegraph -n "__fish_use_subcommand" -l open -d 'Open the output .svg file with default program'
complete -c flamegraph -n "__fish_use_subcommand" -l root -d 'Run with root privileges (using `sudo`)'
complete -c flamegraph -n "__fish_use_subcommand" -l deterministic -d 'Colors are selected such that the color of a function does not change between runs'
complete -c flamegraph -n "__fish_use_subcommand" -s i -l inverted -d 'Plot the flame graph up-side-down'
complete -c flamegraph -n "__fish_use_subcommand" -l reverse -d 'Generate stack-reversed flame graph'
complete -c flamegraph -n "__fish_use_subcommand" -l no-inline -d 'Disable inlining for perf script because of performance issues'
complete -c flamegraph -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c flamegraph -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
